/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.qs.core.parser

import com.qs.core.model.QSArray
import com.qs.core.model.QSObject
import spock.lang.Shared
import spock.lang.Specification
import spock.lang.Unroll;

class QSParserTest extends Specification {

    @Shared
    def expectResultC1 = new QSObject()

    @Unroll
    def "qs parser"(String input, Object output) {
        setup:
        def parser = new QSParser()
        def b2Array = new QSArray()
        def d1d2 = new QSObject()
        d1d2.put("d1", 1)
        d1d2.put("d2", 2)
        b2Array.add(d1d2)
        def b2Object = new QSObject()
        b2Object.put("b2", b2Array)
        expectResultC1.put("c1", b2Object)


        expect:
        ObjectEqual.equals(parser.parse(input), expectResultC1)

        where:
        input                             || output
        "c1[b2][0][d1]=1&c1[b2][0][d2]=2" || expectResultC1
    }

}
